[[redirects]]
  from = "/api/team/02EPUU1T88000000VS5489B1VT0RKM5V"
  to = "https://api-fussball.de/api/team/02EPUU1T88000000VS5489B1VT0RKM5V"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}